name: MiniInvyGui
version: ${project.version}
main: me.faceguy.mini.MiniInvyGui
depend: [Facecore, PlaceholderAPI, ProtocolLib]
softdepend: [HeadDatabase]
api-version: 1.14

commands:
  minigui:
    aliases: [mig]

permissions:
  mini.invy.admin:
      default: false